###################  项目启动端口  ###################
server:
  port: 81

###################  log配置  ###################
logging:
  level:
    ncu.jerry.orangeplus: debug

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: orangeplus-async/src/main/java