###################  项目启动端口  ###################
server:
  port: 82

###################  log配置  ###################
logging:
  level:
    ncu.jerry.orangeplus: debug

###################  spring配置  ###################
spring:
  profiles:
    active: h2dev
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: orangeplus-quartz/src/main/java

---
###################  H2开发环境profile  ###################
spring:
  profiles: h2dev
  #h2
  datasource:
    platform: h2
    schema: classpath:h2sql/schema.sql
    data: classpath:h2sql/data.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none