###################  项目启动端口  ###################
server:
  port: 83

###################  log配置  ###################
logging:
  level:
    ncu.jerry.orangeplus: debug

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: orangeplus-rabbitmq/src/main/java

---
###################  开发环境profile  ###################
spring:
  profiles: dev
  #rabbitmq
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /